### ISSUE TITLE
Running error ：cant find file

### ISSUE THREAD

**Issue by MaYangrui6** [hyrise/rl_index_selection#3]
hi,thank you for your patence:
how to generate this file?
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/tensorflow1/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/project/mayang/rl_index_selection/swirl/__main__.py", line 139, in <module>
    experiment.finish()
  File "/home/ubuntu/project/mayang/rl_index_selection/swirl/experiment.py", line 129, in finish
    self.moving_average_model = self.model_type.load(f"{self.experiment_folder_path}/moving_average_model.zip")
  File "/home/ubuntu/project/mayang/rl_index_selection/stable_baselines/common/base_class.py", line 949, in load
    data, params = cls._load_from_file(load_path, custom_objects=custom_objects)
  File "/home/ubuntu/project/mayang/rl_index_selection/stable_baselines/common/base_class.py", line 652, in _load_from_file
    raise ValueError("Error: the file {} could not be found".format(load_path))
ValueError: Error: the file experiment_results/ID_TPCDS_Test_Experiment/moving_average_model.zip could not be found

**Comment by Bouncner** [comment]
Apparently some of the previous steps did not succeed. Hard to say what the issue is without more information.

**Comment by Tokgoleo** [comment]
same issue, apparently both moving average model and best model are not saved during training. The provided code only produces `final_model.zip`, then encounters error when trying to load these models in `experiment.finish()`.

**Comment by Bensk1** [comment]
I think this can be closed after more than a year.
